### ISSUE TITLE
Codingday: Collect test data

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/bbsnippets#20]
For testing our codebase (manually/automatically), it would be good to have a common test data base containing one or two representative files for all formats commonly used in the lab, including:
- IMD files
- TXT/MCD files
- Standardized acquisition files (i.e., TXT/MCD converted to OME TIFF, panel CSV, etc)
- FCS files
- ...

Ideally for as many software/file format versions as possible, with a small description what the files contain. Also, it would be good to have such data from different tissue types. This would really help development and testing.

**Comment by toobiwankenobi** [comment]
Agreed, @jwindhager. The test data for IMC single-cell data (`cells.csv`) should also include all possible facets of IMC data, e.g. multiple measured variables (`MeanIntensity`, `MeanIntensityCorrected`) and also different stacks (`FullStack`, `FullStackFiltered`). We need to make sure that the IMC workflow covers all possibilities, otherwise, users will be confused.
